import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google';
import "./globals.css";
import Header from "@/src/components/header";
import Footer from "@/src/components/footer";


const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // Adjust weights as needed
  variable: '--font-dm-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Amrk Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} antialiased`}
      >
              {children}
        
      </body>
    </html>
  );
}


//font